### PR TITLE
Very small typo fix. But hopefully helpful

### PR DESCRIPTION
**Pull request by coltonhughes**
This did throw me for a loop when I utilized a switch statement. Small nonetheless.

### CODE REVIEW

**Comment by afriza** [comment]
This variable is, as the filename says, autogenerated.. The typo is in obs-websocket project..

https://github.com/obsproject/obs-websocket/blob/a25427c7cc4b4f0f6ac96ebe2723fc3db8906f22/docs/generated/protocol.json#L2777

**Comment by coltonhughes** [comment]
Interesting. Disregard the PR then.

**Comment by afriza** [comment]
It will be auto-fixed when the library is regenerated to obs-websocket v5.1.0+ since it is fixed upstream in v5.1.0

https://github.com/obsproject/obs-websocket/commit/bc18401fb060f0278e8a2aaad9fa318f5e6b91d8

**Comment by afriza** [comment]
It will be released in OBS Studio v29

**Pull request closed without merging**
